# Site settings
title: Mariano Alfonso | CyberSecurity and Ethical Hacking
description: Articles on CyberSecurity, CTFs and Investigation
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mariano Alfonso
user_description: CyberSecurity and Ethical Hacking
user_title: 0xmaa
email: marianoalfonso80@protonmail.com
LinkedIn_username: https://www.linkedin.com/in/mariano-alfonso-667a60226
# twitter_username: lorem_ipsum
github_username:  0mariano
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
